// SPDX-License-Identifier: Apache-2.0

//! Secret bootstrap.
//!
//! Two secrets are generated by `furcate-minima init` and persisted under
//! `/etc/furcate-pi-minima/`:
//!
//! - `dbpassword` — wallet DB encryption key. **Set once, never
//!   rotated.** Losing this loses the wallet. The crate refuses to
//!   overwrite an existing `dbpassword` file; the operator must move it
//!   aside manually to force a fresh install. File mode `0600`, owned
//!   by user `furcate-minima`.
//! - `rpcpassword` — HTTP Basic Auth password for the local RPC. File
//!   mode `0600`, group `furcate-minima` so processes in that group
//!   (e.g. an attestor running as a non-root service user) can read it.
//!
//! Both are 32 random bytes, hex-encoded (64 chars). Generation uses
//! `getrandom` directly — no `rand` ceremony for a one-shot secret.
//!
//! Minima's RPC password parser restricts to alphanumeric (see
//! `backup.java`'s docstring quoted in `docs/minima-reference.md` §2.3);
//! hex output already satisfies that.

use std::path::Path;

use crate::error::Error;

/// Generate a 32-byte hex secret string (64 ASCII chars).
///
/// Crash-on-fail because `getrandom` failing means the OS entropy
/// source is broken, which is unrecoverable from inside `init`.
///
/// # Panics
///
/// Panics if `getrandom` cannot pull entropy from the OS. On Linux
/// that means `/dev/urandom` is unavailable — there is no graceful
/// recovery from that state inside `furcate-minima init`.
#[must_use]
pub fn generate_hex_secret() -> String {
    let mut buf = [0u8; 32];
    getrandom::getrandom(&mut buf).expect("OS entropy source unavailable");
    hex::encode(buf)
}

/// Write `secret` to `path` with mode 0600, refusing to overwrite.
///
/// If the file already exists, returns [`Error::SecretAlreadyExists`].
/// This is load-bearing for `dbpassword`: silently rotating it would
/// brick the wallet.
///
/// Uses `O_CREAT | O_EXCL | O_WRONLY` so the "refuse to overwrite"
/// guarantee is atomic against the filesystem — no TOCTOU window
/// between an `exists()` check and the write.
///
/// # Errors
///
/// Returns [`Error::SecretAlreadyExists`] if `path` is already
/// present, or [`Error::Io`] for other filesystem failures.
#[cfg(target_os = "linux")]
pub fn write_secret_no_overwrite(path: &Path, secret: &str) -> Result<(), Error> {
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;

    let mut file = match std::fs::OpenOptions::new()
        .write(true)
        .create_new(true) // O_CREAT | O_EXCL
        .mode(0o600)
        .open(path)
    {
        Ok(f) => f,
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
            return Err(Error::SecretAlreadyExists(path.to_path_buf()));
        }
        Err(e) => return Err(e.into()),
    };
    file.write_all(secret.as_bytes())?;
    // Trailing newline so editors don't choke if an operator ever opens
    // the file. Minima's env-file parser ignores trailing whitespace.
    file.write_all(b"\n")?;
    file.sync_all()?;
    Ok(())
}

/// Non-Linux stub.
///
/// The crate targets Pi-class Linux; on other platforms the function
/// compiles but refuses at runtime so dev-environment tools
/// (rust-analyzer, doc builds on docs.rs's `x86_64` sandbox) still see
/// the symbol.
///
/// # Errors
///
/// Always returns [`Error::Preflight`] — secret bootstrap is a
/// Linux-only operation.
#[cfg(not(target_os = "linux"))]
pub fn write_secret_no_overwrite(_path: &Path, _secret: &str) -> Result<(), Error> {
    Err(Error::Preflight(
        "secret bootstrap is Linux-only — this crate targets Pi-class hardware".into(),
    ))
}

/// Read a previously-persisted secret. Strips trailing whitespace.
///
/// # Errors
///
/// Returns [`Error::PermissionDenied`] specifically when the file
/// exists but the calling process lacks permission to read it (the
/// typical case: file is 0600, owned by `furcate-minima`, caller is
/// not in the group). [`Error::NotInstalled`] if the file is missing.
/// [`Error::Io`] for other filesystem failures.
pub fn read_secret(path: &Path) -> Result<String, Error> {
    match std::fs::read_to_string(path) {
        Ok(s) => Ok(s.trim().to_string()),
        Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            Err(Error::PermissionDenied(path.to_path_buf()))
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            Err(Error::NotInstalled(path.to_path_buf()))
        }
        Err(e) => Err(e.into()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_secret_is_64_chars() {
        let s = generate_hex_secret();
        assert_eq!(s.len(), 64);
        assert!(s.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn two_secrets_differ() {
        assert_ne!(generate_hex_secret(), generate_hex_secret());
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn write_then_read_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("secret");
        let secret = "abc123";
        write_secret_no_overwrite(&path, secret).unwrap();
        let read = read_secret(&path).unwrap();
        assert_eq!(read, secret);
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn refuses_to_overwrite_existing_secret() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("secret");
        write_secret_no_overwrite(&path, "first").unwrap();
        let err = write_secret_no_overwrite(&path, "second").unwrap_err();
        assert!(matches!(err, Error::SecretAlreadyExists(_)));
        // First value still on disk.
        assert_eq!(read_secret(&path).unwrap(), "first");
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn written_file_has_mode_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("secret");
        write_secret_no_overwrite(&path, "x").unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        // Mode field includes file type bits; mask down to permissions.
        assert_eq!(mode & 0o777, 0o600);
    }
}
